[package]
name = "kronicle"
version = "0.1.0"
authors = ["Atra <57003922+estatra@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
job_scheduler = "1.2.1"